---
title: "dimension_reduce"
author: "Yunrui Lu"
date: "11/06/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggfortify)
library(factoextra)
library(FactoMineR)
library(tsne)
library(umap)
library(pROC)
library(randomForest)
```

```{r}
# raw.data = read.table('data.csv', sep = ',', header=TRUE)
# raw.label = read.table('labels.csv', sep = ',', header=TRUE)
```

\section{PCA}

```{r}
data.pca = read.table('data.csv', sep = ',', header=TRUE)
label.pca = read.table('labels.csv', sep = ',', header=TRUE)
```

```{r}
com.pca <- prcomp(data.pca[,2:20532], center = TRUE)
```

```{r}
library(ggbiplot)
ggscreeplot(com.pca)
```

```{r}
test = com.pca$x
dr.pca = data.frame(class = label.pca$Class,
                    PC1 = test[, 1],
                    PC2 = test[, 2])
```

```{r}
write.csv(dr.pca,file="dr_pca.csv",quote=F,row.names = F)
```

\section{TSNE}

```{r}
library(tsne)
colors = rainbow(length(unique(label.tsne$Class)))
names(colors) = unique(label.tsne$Class)
head(colors)
```

```{r}
tsne.out = tsne(data.tsne[,2:20532],k=2,perplexity=50)
```

Please don't run this code on your own computer. It require really large computational resource.

Run this on HPC or other.

```{r}
dr.tsne = data.frame(class = label.tsne$Class,
                     tsne1 = tsne.out[, 1],
                     tsne2 = tsne.out[, 2])
write.csv(dr.tsne,file="dr_tsne.csv",quote=F,row.names = F)
```

Please ingore this method following.

```{r}
# library(tsne)
library(Rtsne)
data.tsne = read.table('data.csv', sep = ',', header=TRUE)
label.tsne = read.table('labels.csv', sep = ',', header=TRUE)
```

```{r}
# data.tsne = data.tsne[, -1]
# data.tsne.matrix = as.matrix(data.tsne[,1:20532])
# head(data.tsne.matrix)
```

```{r}
set.seed(42)
Rtsne.out <- Rtsne(data.tsne[,2:20532],dims=2, perplexity=30)
dr.tsne = data.frame(class = label.tsne$Class,
                     tsne1 = Rtsne.out$Y[, 1],
                     tsne2 = Rtsne.out$Y[, 2])
write.csv(dr.tsne,file="dr_Rtsne.csv",quote=F,row.names = F)
```

\section{UMAP}

```{r}
library(umap)
data.umap = read.table('data.csv', sep = ',', header=TRUE)
label.umap = read.table('labels.csv', sep = ',', header=TRUE)
```

```{r}
data.umap.matrix = as.matrix(data.umap[,2:20532])
```

```{r}
data.umap.output = umap(data.umap.matrix)
```

```{r}
head(data.umap.output$layout)
```

```{r}
dr.umap = data.frame(class = label.umap$Class,
                     umap1 = data.umap.output$layout[, 1], 
                     umap2 = data.umap.output$layout[, 2])
```

```{r}
write.csv(dr.umap,file="dr_umap.csv",quote=F,row.names = F)
```


