---
title: "PCA_tSNE_UMAP"
author: "Jiahui Li"
date: "11/2/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
pca=read.csv("pca_dimension_reduced.csv",header=TRUE,sep=",")
colnames(pca)=c("num","PCA_1","PCA_2","target")
T=unique(pca$target)
tar_cols<-c("#de8f6e","#aac0aa","#2a1a1f","#bb0a21","#087e8b")
names(tar_cols)<-levels(pca$target)
ggplot(pca,aes(x=`PCA_1`,y=`PCA_2`,color=target))+
  geom_point()+ 
  labs(x="PCA_1",y="PCA_2")+
  scale_color_manual(values=tar_cols)+ 
  theme_classic()

pca_mean1=c()
pca_mean2=c()
pca_var1=c()
pca_var2=c()
for(i in 1:5){
  pca_mean1[i]=mean(pca[which(pca$target==T[i]),]$PCA_1)
  pca_mean2[i]=mean(pca[which(pca$target==T[i]),]$PCA_2)
  pca_var1[i]=var(pca[which(pca$target==T[i]),]$PCA_1)
  pca_var2[i]=var(pca[which(pca$target==T[i]),]$PCA_2)
}
pcameasure=data.frame(T,pca_mean1,pca_mean2,pca_var1,pca_var2)
head(pcameasure)
plot(density(pca$PCA_1))
lines(density(pca$PCA_2),col="red")


  # library(ggplot2)
  # colnames(data)=c("target","dr_1","dr_2")
  # T=unique(data$target)
  # ggplot(data,aes(x=`dr_1`,y=`dr_2`,color=target))+
  #   geom_point()+ 
  #   labs(x="dr_1",y="dr_2")+ theme_classic()
  # 
  # 
  # dr_mean1=c()
  # dr_mean2=c()
  # dr_var1=c()
  # dr_var2=c()
  # for(i in 1:5){
  #   dr_mean1[i]=mean(data[which(data$target==T[i]),]$dr_1)
  #   dr_mean2[i]=mean(data[which(data$target==T[i]),]$dr_2)
  #   dr_var1[i]=var(data[which(data$target==T[i]),]$dr_1)
  #   dr_var2[i]=var(data[which(data$target==T[i]),]$dr_2)
  # }
  # measure=data.frame(T,dr_mean1,dr_mean2,dr_var1,dr_var2)
  # head(measure)
  # plot(density(data$dr_1))
  # lines(density(data$dr_2),col="red")
```

```{r}
tsne=read.csv("dr_tsne.csv",header=TRUE,sep=",")
colnames(tsne)=c("target","tSNE_1","tSNE_2")

tar_cols<-c("#de8f6e","#aac0aa","#2a1a1f","#bb0a21","#087e8b")
names(tar_cols)<-levels(tsne$target)
ggplot(tsne,aes(x=`tSNE_1`,y=`tSNE_2`,color=target))+
  geom_point()+ 
  labs(x="tSNE_1",y="tSNE_2")+
  scale_color_manual(values=tar_cols)+ 
  theme_classic()

tsne_mean1=c()
tsne_mean2=c()
tsne_var1=c()
tsne_var2=c()
for(i in 1:5){
  tsne_mean1[i]=mean(tsne[which(tsne$target==T[i]),]$tSNE_1)
  tsne_mean2[i]=mean(tsne[which(tsne$target==T[i]),]$tSNE_2)
  tsne_var1[i]=var(tsne[which(tsne$target==T[i]),]$tSNE_1)
  tsne_var2[i]=var(tsne[which(tsne$target==T[i]),]$tSNE_2)
}
tsnemeasure=data.frame(T,tsne_mean1,tsne_mean2,tsne_var1,tsne_var2)
head(tsnemeasure)
plot(density(tsne$tSNE_1))
lines(density(tsne$tSNE_2),col="red")
```



```{r}
umap=read.csv("dr_umap.csv",header=TRUE,sep=",")
colnames(umap)=c("target","UMAP_1","UMAP_2")


tar_cols<-c("#de8f6e","#aac0aa","#2a1a1f","#bb0a21","#087e8b")
names(tar_cols)<-levels(umap$target)
ggplot(umap,aes(x=`UMAP_1`,y=`UMAP_2`,color=target))+
  geom_point()+
  labs(x="UMAP_1",y="UMAP_2")+
  scale_color_manual(values=tar_cols)+ 
  theme_classic()

umap_mean1=c()
umap_mean2=c()
umap_var1=c()
umap_var2=c()
for(i in 1:5){
  umap_mean1[i]=mean(umap[which(tsne$target==T[i]),]$UMAP_1)
  umap_mean2[i]=mean(umap[which(tsne$target==T[i]),]$UMAP_2)
  umap_var1[i]=var(umap[which(tsne$target==T[i]),]$UMAP_1)
  umap_var2[i]=var(umap[which(tsne$target==T[i]),]$UMAP_2)
}
umapmeasure=data.frame(T,umap_mean1,umap_mean2,umap_var1,umap_var2)
head(umapmeasure)
plot(density(umap$UMAP_1))
lines(density(umap$UMAP_2),col="red")
```